// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkvfquiicfqanvxuhrrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrdmZxdWlpY2ZxYW52eHVocnJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NTY1MTMsImV4cCI6MjA2NzUzMjUxM30.k84RZCmABELbXnPJ83LKHYHVdZGR0LD5ZlcQQ5btVEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});